import React from 'react';

export type Puzzle = {
  id: number;
  title: string;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
};

export const ALL_PUZZLES: Puzzle[] = [
  {
    id: 1,
    title: "False Connection",
    question: "Statement 1: All Lions are Cats.\nStatement 2: Some Cats are Blue.\nConclusion: Therefore, some Lions are Blue.",
    options: ["Logic is TRUE", "Logic is FALSE"],
    answer: "Logic is FALSE",
    explanation: "Standard Syllogism trap. Just because some cats are blue doesn't mean lions (who are cats) must be blue.",
  },
  {
    id: 2,
    title: "Sequence Breaker",
    question: "O, T, T, F, F, S, S, _?",
    options: ["S", "E", "N", "T"],
    answer: "E",
    explanation: "These are the first letters of numbers: One, Two, Three, Four, Five, Six, Seven. The next is Eight (E).",
  },
  {
    id: 3,
    title: "Weight Paradox",
    question: "If 3 Apples weigh the same as 2 Oranges, and 1 Banana is heavier than 1 Orange, which fruit is the heaviest?",
    options: ["Apple", "Orange", "Banana"],
    answer: "Banana",
    explanation: "3A = 2O implies 1O > 1A. Since B > O, then B > O > A. Banana is the heaviest.",
  },
  {
    id: 4,
    title: "Mirror Time",
    question: "A mirror shows an analog clock at 3:45. What is the real time?",
    options: ["3:45", "9:15", "8:15", "9:45"],
    answer: "8:15",
    explanation: "Real Time = 11:60 - Mirror Time. 11:60 - 3:45 = 8:15.",
  },
  {
    id: 5,
    title: "Letter Math",
    question: "A + A = B\nB + A = 6\nWhat is the value of B?",
    options: ["2", "4", "3", "6"],
    answer: "4",
    explanation: "A=2, B=4. 2+2=4 and 4+2=6.",
  },
  {
    id: 6,
    title: "Elevator Logic",
    question: "A man lives on the 10th floor. On rainy days he takes the lift to the 10th. On sunny days, he goes to the 7th and walks the rest. Why?",
    options: ["He likes exercise", "He is short", "The lift is broken", "He visits a friend"],
    answer: "He is short",
    explanation: "He can only reach the 10th button with his umbrella. On sunny days he lacks it and only reaches the 7th.",
  },
  {
    id: 7,
    title: "Silent Syllables",
    question: "How many silent letters are in the word 'PNEUMONIA'?",
    options: ["0", "1", "2", "3"],
    answer: "1",
    explanation: "The 'P' is silent.",
  },
  {
    id: 8,
    title: "Odd Shape Out",
    question: "Which of these does NOT belong?",
    options: ["Circle", "Sphere", "Triangle", "Square"],
    answer: "Sphere",
    explanation: "A Sphere is 3D; the others are 2D shapes.",
  },
  {
    id: 9,
    title: "The Color Path",
    question: "Instruction: Pick the word where Word and Color match.",
    options: ["RED (in Blue)", "GREEN (in Green)", "YELLOW (in Red)", "BLUE (in Yellow)"],
    answer: "GREEN (in Green)",
    explanation: "This tests inhibition. Only Green matches both word and color.",
  },
  {
    id: 10,
    title: "Logic Trap 2",
    question: "A plane crashes on the border of US and Canada. Where do you bury the survivors?",
    options: ["USA", "Canada", "Neutral Ground", "You don't"],
    answer: "You don't",
    explanation: "You don't bury survivors!",
  },
  {
    id: 11,
    title: "Family Ties",
    question: "Ek baccha 'A' aur 'B' ka beta hai, lekin 'B' uska baap nahi hai. Toh 'B' kaun hai?",
    options: ["Chacha", "Mausi", "Maa", "Padosi"],
    answer: "Maa",
    explanation: "Agar B baap nahi hai toh wo Maa hi hogi.",
  },
  {
    id: 12,
    title: "The Eternal Arrival",
    question: "Wo kya hai jo hamesha aata hai lekin kabhi pahunchta nahi?",
    options: ["Train", "Kal (Tomorrow)", "Baarish", "Chitti"],
    answer: "Kal (Tomorrow)",
    explanation: "Kal (Tomorrow) hamesha aane wala hota hai par jab aata hai toh wo 'Aaj' ban jata hai.",
  },
  {
    id: 13,
    title: "The Dinner Table",
    question: "Ek mez (Table) par 2 maayein aur 2 betiyan khana kha rahi hain, par wahan sirf 3 hi log hain. Kaise?",
    options: ["Ek bhoot hai", "Nani, Maa aur Beti", "Ek padosi hai", "Rishta galat hai"],
    answer: "Nani, Maa aur Beti",
    explanation: "Nani, unki beti (jo maa hai), aur unki beti (jo poti/beti hai). 2 maayein aur 2 betiyan pure ho gaye.",
  },
  {
    id: 14,
    title: "The Room Trap",
    question: "Ek room mein 3 log hain. Aapne 2 ko maar diya. Ab room mein kitne log bache?",
    options: ["1", "2", "3", "4"],
    answer: "4",
    explanation: "Aap khud, 2 lashein, aur 1 jo bach gaya = 4 log (living and dead) room mein hain.",
  },
  {
    id: 15,
    title: "Broken Utility",
    question: "Wo kya hai jo toote bina kaam nahi karta?",
    options: ["Dil", "Anda (Egg)", "Pencil", "Khilauna"],
    answer: "Anda (Egg)",
    explanation: "Ande ko istemal karne ke liye use todna hi padta hai.",
  },
  {
    id: 16,
    title: "Wall Logic",
    question: "Agar 8 log ek deewar ko banane mein 10 ghante lete hain, toh wahi deewar banane mein 4 log kitna time lenge?",
    options: ["20 ghante", "5 ghante", "Zero", "40 ghante"],
    answer: "Zero",
    explanation: "Deewar toh pehle hi ban chuki hai!",
  },
  {
    id: 17,
    title: "Blind Sight",
    question: "Mere paas aankhen hain par main dekh nahi sakta. Main kaun hoon?",
    options: ["Andha aadmi", "Sui (Needle)", "Aloo (Potato)", "B aur C dono"],
    answer: "B aur C dono",
    explanation: "Sui ki 'aankh' (naka) aur Aloo ki bhi 'aankh' hoti hai.",
  },
  {
    id: 18,
    title: "Dictionary Order",
    question: "Wo kaunsi jagah hai jahan Friday, Thursday se pehle aata hai?",
    options: ["Mars", "Dictionary", "Sapne mein", "Dusra desh"],
    answer: "Dictionary",
    explanation: "Dictionary mein F (Friday) T (Thursday) se pehle aata hai.",
  },
  {
    id: 19,
    title: "Increasing Darkness",
    question: "Wo kya hai jo jitna zyada badhta hai, utna hi kam dikhta hai?",
    options: ["Paisa", "Andhera", "Umra", "Height"],
    answer: "Andhera",
    explanation: "Andhera jitna badhega, utna hi kam dikhayi dega.",
  },
  {
    id: 20,
    title: "The Crash Paradox",
    question: "Ek airplane crash hua aur har ek single person mar gaya. Phir bhi 2 log bach gaye. Kaise?",
    options: ["Plane ke bahar the", "Married couple", "Wo pilot the", "Bhoot ban gaye"],
    answer: "Married couple",
    explanation: "Kyuki wo 'Married' the, 'Single' nahi.",
  },
  {
    id: 21,
    title: "Hen Math",
    question: "3 murgiyan 3 din mein 3 ande deti hain. Toh 12 murgiyan 12 din mein kitne ande dengi?",
    options: ["12", "36", "48", "144"],
    answer: "48",
    explanation: "1 murgi 3 din mein 1 anda deti hai. 12 murgiyan 3 din mein 12 ande dengi. 12 din mein (12*4) = 48.",
  },
  {
    id: 22,
    title: "The Apple Thief",
    question: "Ek tokri mein 10 seb hain. Aapne 3 seb nikaal liye. Ab aapke paas kitne seb hain?",
    options: ["7", "10", "3", "13"],
    answer: "3",
    explanation: "Jo 3 seb aapne nikaale, wahi aapke paas hain!",
  },
  {
    id: 23,
    title: "Doctor's Prescription",
    question: "Agar ek doctor aapko 3 tablets deta hai aur kehta hai har adhe ghante baad ek leni hai. Kitna time lagega?",
    options: ["1.5 ghante", "1 ghanta", "30 min", "2 ghante"],
    answer: "1 ghanta",
    explanation: "Pehli abhi (0 min), dusri 30 min baad, teesri 60 min baad.",
  },
  {
    id: 24,
    title: "Letter Count",
    question: "How many letters are in 'M-A-N-G-O'?",
    options: ["4", "5", "6", "1"],
    answer: "5",
    explanation: "M-A-N-G-O has exactly 5 letters.",
  },
  {
    id: 25,
    title: "The Drying Towel",
    question: "Wo kya hai jo jitna sukhta hai, utna hi geela hota jata hai?",
    options: ["Pani", "Towel", "Baadal", "Suraj"],
    answer: "Towel",
    explanation: "Towel cheezon ko sukhata hai isliye wo khud geela hota jata hai.",
  },
  {
    id: 26,
    title: "Infinite Treasure",
    question: "Wo kaunsa khazana hai jise jitna baanto utna badhta hai?",
    options: ["Paisa", "Khana", "Gyan (Knowledge)", "Kapde"],
    answer: "Gyan (Knowledge)",
    explanation: "Gyan (Knowledge) baantne se hamesha badhta hai.",
  },
  {
    id: 27,
    title: "Billi ka Naam",
    question: "Ek billi ke 3 bacche hain: January, February aur March. Billi ka naam kya hai?",
    options: ["April", "What", "Kitty", "Pussy"],
    answer: "What",
    explanation: "Sentence ko dhyan se padhein: 'Billi ka naam (What) hai'.",
  },
  {
    id: 28,
    title: "Invisible Presence",
    question: "Wo kya hai jo hamesha aapke samne hota hai par dikhta nahi?",
    options: ["Hawa", "Bhavishya (Future)", "Palkein", "B aur C dono"],
    answer: "B aur C dono",
    explanation: "Bhavishya aur Palkein hamesha samne hote hain par dikhte nahi.",
  },
  {
    id: 29,
    title: "Un-eatable Purchase",
    question: "Wo kaunsa phal/cheez hai jo hum kharidte toh khane ke liye hain par khate nahi?",
    options: ["Plate", "Chammach", "Dono", "Kela"],
    answer: "Dono",
    explanation: "Plate aur Chammach khane ke 'liye' kharidte hain par unhe khate nahi.",
  },
  {
    id: 30,
    title: "Race Position",
    question: "Agar aap ek race mein dusre (2nd) number wale ko piche chhod dete hain, toh aap kis number par honge?",
    options: ["1st", "2nd", "3rd", "Last"],
    answer: "2nd",
    explanation: "Aapne 2nd wale ki jagah le li, isliye aap ab 2nd position par hain.",
  },
  {
    id: 31,
    title: "The Bald Man",
    question: "Ek aadmi barish mein bina umbrella aur bina hat ke bahr gaya, par uske ek bhi baal (hair) geele nahi hue. Kaise?",
    options: ["Wo bhaag raha tha", "Wo ganja (bald) tha", "Barish halki thi", "Wo chhat ke niche tha"],
    answer: "Wo ganja (bald) tha",
    explanation: "Agar sar par baal hi nahi honge toh geele kaise honge?",
  },
  {
    id: 32,
    title: "The Motionless Road",
    question: "Wo kya hai jo ek jagah se dusri jagah jati hai par hilti nahi?",
    options: ["Bus", "Sadak (Road)", "Train", "Hawa"],
    answer: "Sadak (Road)",
    explanation: "Sadak ek hi jagah rahti hai par wo aapko door tak le jati hai.",
  },
  {
    id: 33,
    title: "Huge Hands",
    question: "Agar aapke paas 3 seb aur 4 santre ek hath mein hain, aur 4 seb aur 3 santre dusre hath mein, toh aapke paas kya hai?",
    options: ["Fruit salad", "Bahut bade hath", "14 phal", "Kuch nahi"],
    answer: "Bahut bade hath",
    explanation: "Itne saare phal normal hath mein nahi aa sakte, toh aapke hath bahut bade hain!",
  },
  {
    id: 34,
    title: "Rain Down",
    question: "Wo kya hai jo hamesha niche aata hai par kabhi upar nahi jata?",
    options: ["Lift", "Baarish", "Ball", "Umra (Age)"],
    answer: "Baarish",
    explanation: "Baarish hamesha upar se niche girti hai.",
  },
  {
    id: 35,
    title: "Clean Darkness",
    question: "Wo kya hai jo jitna zyada saaf (clean) hota hai, utna hi kaala dikhta hai?",
    options: ["Kapde", "Blackboard", "Bartan", "Jootey"],
    answer: "Blackboard",
    explanation: "Blackboard jab saaf hota hai toh wo poora kaala hota hai.",
  },
  {
    id: 36,
    title: "Elephant Logic",
    question: "Ek haathi (Elephant) ko Fridge mein kaise rakhenge?",
    options: ["Fridge bada karke", "Khola, rakha, band kiya", "Haathi chota karke", "Mumkin nahi"],
    answer: "Khola, rakha, band kiya",
    explanation: "Step 1: Fridge kholo. Step 2: Haathi rakho. Step 3: Gate band karo.",
  },
  {
    id: 37,
    title: "Meeting Absentee",
    question: "Jungle ki meeting mein saare jaanwar aaye, par ek nahi aaya. Kaun?",
    options: ["Sher", "Haathi", "Bandar", "Lomdi"],
    answer: "Haathi",
    explanation: "Kyunki haathi abhi pichle sawal ke fridge mein band hai!",
  },
  {
    id: 38,
    title: "Safe River",
    question: "Nadi mein ek magarmach (crocodile) hai, aapko nadi paar karni hai par boat nahi hai. Kaise karenge?",
    options: ["Wood use karke", "Tair kar (Swim)", "Helicopter se", "Intezar karke"],
    answer: "Tair kar (Swim)",
    explanation: "Aap tair kar ja sakte hain kyunki magarmach bhi jungle ki meeting mein gaya hai.",
  },
  {
    id: 39,
    title: "Teeth Cycle",
    question: "Wo kya hai jo aapko ek baar free milti hai, dusri baar bhi free, par teesri baar kharidni padti hai?",
    options: ["Khana", "Daant (Teeth)", "Saans", "Education"],
    answer: "Daant (Teeth)",
    explanation: "Milk teeth aur permanent teeth free hain, uske baad artificial lagwane padte hain.",
  },
  {
    id: 40,
    title: "Neck but No Head",
    question: "Wo kaunsi cheez hai jiska gala (neck) hai par sir (head) nahi?",
    options: ["Bottle", "Snake", "Shirt", "Guitar"],
    answer: "Bottle",
    explanation: "Bottle ki 'neck' hoti hai par head nahi.",
  },
  {
    id: 41,
    title: "Seven Even",
    question: "Main ek odd number hoon. Mujhse ek letter nikaal do aur main 'Even' ban jata hoon. Main kaun hoon?",
    options: ["3", "5", "7", "9"],
    answer: "7",
    explanation: "SEVEN mein se 'S' nikaal do toh wo 'EVEN' ban jata hai.",
  },
  {
    id: 42,
    title: "8 to 1000",
    question: "8 ko 8 baar kaise plus (+) karenge ki answer 1000 aaye?",
    options: ["Impossible", "888+88+8+8+8", "8x8x8", "88+88"],
    answer: "888+88+8+8+8",
    explanation: "888 + 88 + 8 + 8 + 8 = 1000.",
  },
  {
    id: 43,
    title: "Survival Logic",
    question: "Mere paas 10 murgiyan hain, sab mar gayin sivaye 9 ke. Ab kitni murgiyan hain?",
    options: ["1", "0", "10", "9"],
    answer: "9",
    explanation: "'Sivaye 9' ka matlab 9 zinda bachi hain.",
  },
  {
    id: 44,
    title: "Frog in a Well",
    question: "Agar kuan 10ft gehra hai, mendhak roz 3ft upar chadhta hai aur 2ft phisal jata hai. Wo kab bahar aayega?",
    options: ["10 din", "9 din", "8 din", "7 din"],
    answer: "8 din",
    explanation: "8th day par wo 3ft ki jump maarke seedha bahar nikal jayega, phislega nahi.",
  },
  {
    id: 45,
    title: "Weight vs Volume",
    question: "1kg loha aur 1kg rui (cotton) mein se zyada jagah kaun gherega?",
    options: ["Loha", "Rui", "Dono barabar", "Koi nahi"],
    answer: "Rui",
    explanation: "Wazan barabar hai, par rui ki density kam hai toh wo zyada jagah (volume) leti hai.",
  },
  {
    id: 46,
    title: "BODMAS Check",
    question: "2 + 2 / 2 = ?",
    options: ["2", "3", "4", "1"],
    answer: "3",
    explanation: "Rule ke mutabik pehle divide (2/2=1) phir plus (2+1=3).",
  },
  {
    id: 47,
    title: "Zero in 100",
    question: "Wo kya hai jo 100 saal mein sirf ek baar aata hai?",
    options: ["Birthday", "Century", "'0' (Zero)", "Leap Year"],
    answer: "'0' (Zero)",
    explanation: "Number 100 likhne mein '0' sirf 100 ki series mein hi aata hai (interpretation game).",
  },
  {
    id: 48,
    title: "Mirror Math",
    question: "1 matchstick se bina tode '4' kaise banayenge?",
    options: ["Mirror ke samne", "Roman IV", "Plus sign", "Nahi ban sakta"],
    answer: "Mirror ke samne",
    explanation: "Stick ko mirror ke samne aise rakho ki IV dikhe.",
  },
  {
    id: 49,
    title: "Count the 9s",
    question: "1 se 10 tak kitne 9 hote hain?",
    options: ["1", "0", "2", "9"],
    answer: "1",
    explanation: "Sirf ek hi 9 aata hai.",
  },
  {
    id: 50,
    title: "Blowing Candles",
    question: "10 mombatti jal rahi thin, hawa se 3 bujh gayin. Subah kitni bachi rahengi?",
    options: ["7", "10", "3", "0"],
    answer: "3",
    explanation: "Jo 3 bujh gayin wo bachi rahengi, baki 7 pighal kar khatam ho jayengi.",
  },
  {
    id: 51,
    title: "Short Word",
    question: "Wo kaunsa word hai jo English mein hamesha 'Short' padha jata hai?",
    options: ["Small", "Little", "Short", "Tiny"],
    answer: "Short",
    explanation: "Short word ko hum 'Short' hi padhte hain.",
  },
  {
    id: 52,
    title: "The Teapot",
    question: "Wo kya hai jo 'T' se shuru aur 'T' par khatam hota hai aur andar 'T' (Tea) hoti hai?",
    options: ["Teapot", "Tent", "Target", "Toast"],
    answer: "Teapot",
    explanation: "T-e-a-p-o-t.",
  },
  {
    id: 53,
    title: "Pangram",
    question: "Inmein se kaunsa sentence saare A to Z alphabets use karta hai?",
    options: ["I love alphabet", "The quick brown fox jumps over the lazy dog", "ABC...Z", "A to Z is here"],
    answer: "The quick brown fox jumps over the lazy dog",
    explanation: "Is sentence mein English ke saare 26 letters aate hain.",
  },
  {
    id: 54,
    title: "December E",
    question: "Wo kya hai jo 'December' mein 2 baar aata hai par saal mein ek baar bhi nahi?",
    options: ["Thand", "Letter 'E'", "Holiday", "Letter 'D'"],
    answer: "Letter 'E'",
    explanation: "D-e-c-e-m-b-e-r (do 'e' hain). YEAR mein koi 'e' nahi (interpretation).",
  },
  {
    id: 55,
    title: "Teeth but No Bite",
    question: "Wo kya hai jiske paas 'Teeth' hain par wo kaat nahi sakta?",
    options: ["Comb (Kanghi)", "Saw (Aari)", "Zip", "All of these"],
    answer: "All of these",
    explanation: "Kanghi, aari aur zip sabke 'teeth' hote hain.",
  },
  {
    id: 56,
    title: "Cat Corners",
    question: "Kamre mein 4 kone hain, har kone mein 1 billi. Har billi ke samne 3 billiyan. Total kitni?",
    options: ["12", "4", "8", "16"],
    answer: "4",
    explanation: "Kyunki har billi baaki 3 billiyon ko dekh rahi hai.",
  },
  {
    id: 57,
    title: "The Bus Driver",
    question: "Aapka naam 'A' hai. Aap bus chala rahe hain. Bus mein 10 log chadhe. Driver ka naam kya hai?",
    options: ["Driver", "A", "B", "Pata nahi"],
    answer: "A",
    explanation: "Kyunki 'Aap' bus chala rahe hain, toh aapka naam 'A' hi driver ka naam hai.",
  },
  {
    id: 58,
    title: "Sheep Math",
    question: "17 bhedein thin, sab mar gayin sivaye 7 ke. Kitni bachi?",
    options: ["10", "17", "7", "0"],
    answer: "7",
    explanation: "Sivaye 7 ka matlab sirf 7 hi zinda hain.",
  },
  {
    id: 59,
    title: "Made to Break",
    question: "Wo kya hai jo tootne ke liye hi banti hai?",
    options: ["Glass", "Record", "Biscuit", "Pencil"],
    answer: "Record",
    explanation: "Records banaye hi jate hain taaki koi unhe tode.",
  },
  {
    id: 60,
    title: "Rising Smoke",
    question: "Wo kya hai jo niche se upar jati hai par upar se niche nahi aati?",
    options: ["Smoke (Dhuaan)", "Ball", "Kite", "Gas"],
    answer: "Smoke (Dhuaan)",
    explanation: "Dhuaan hamesha upar uthta hai.",
  },
  {
    id: 61,
    title: "Murderer Search",
    question: "Victim ne marte waqt '4' likha tha. Suspects: Jan, April, June, Sept. Murderer kaun hai?",
    options: ["Jan", "April", "June", "Sept"],
    answer: "April",
    explanation: "April saal ka 4th month hota hai.",
  },
  {
    id: 62,
    title: "Clock Life",
    question: "Wo kya hai jo bina pairon ke chalti hai aur bina hath ke marti hai?",
    options: ["Ghadi (Clock)", "Hawa", "Bijli", "Police"],
    answer: "Ghadi (Clock)",
    explanation: "Ghadi chalti rehti hai aur uski bells/alarm 'bajti' (beat) hai.",
  },
  {
    id: 63,
    title: "Aged Man",
    question: "Wo kya hai jo subah 4 pairon par, dopahar ko 2 par, aur sham ko 3 par chalta hai?",
    options: ["Robot", "Insaan", "Janwar", "Alien"],
    answer: "Insaan",
    explanation: "Bachpan (crawl-4), Jawani (walk-2), Budhapa (cane-3).",
  },
  {
    id: 64,
    title: "The Gift of Respect",
    question: "Wo kya hai jo aapko tabhi milti hai jab aap use kisi ko dete hain?",
    options: ["Gift", "Respect", "Dhoka", "Udhaar"],
    answer: "Respect",
    explanation: "Izzat dene se hi milti hai.",
  },
  {
    id: 65,
    title: "Keys but No Doors",
    question: "Kiske paas bohot saare 'Keys' hain par wo ek bhi darwaza nahi khol sakta?",
    options: ["Keyboard", "Piano", "Dono", "Locksmith"],
    answer: "Dono",
    explanation: "Keyboard aur Piano dono mein keys hoti hain par lock nahi khul sakte.",
  },
  {
    id: 66,
    title: "Holey Weight",
    question: "Wo kya hai jo jitna zyada hota hai, utna hi kam wazan hota hai?",
    options: ["Hawa", "Holes (Chhed)", "Light", "Water"],
    answer: "Holes (Chhed)",
    explanation: "Kisi cheez mein jitne zyada chhed honge, uska wazan utna hi kam hoga.",
  },
  {
    id: 67,
    title: "Silent Ears",
    question: "Wo kya hai jo sun sakta hai par bol nahi sakta?",
    options: ["Kaan (Ear)", "Deewar", "Mobile", "Mirror"],
    answer: "Kaan (Ear)",
    explanation: "Kaan sunte hain par bolte nahi.",
  },
  {
    id: 68,
    title: "The Wet Stone",
    question: "Agar kuan mein ek patthar fenka jaye toh kya hoga?",
    options: ["Patthar tut jayega", "Patthar geela ho jayega", "Patthar gayab", "Kuan bhar jayega"],
    answer: "Patthar geela ho jayega",
    explanation: "Kuan mein pani hai toh patthar geela hi hoga.",
  },
  {
    id: 69,
    title: "Wedding Count",
    question: "Wo kaunsi jagah hai jahan 100 log jate hain aur 101 bahar aate hain?",
    options: ["Hospital", "Wedding", "School", "Bus"],
    answer: "Wedding",
    explanation: "Dulhan ko vida kar ke sath laya jata hai.",
  },
  {
    id: 70,
    title: "Card Game",
    question: "Wo kya hai jise aap kaat-te hain, peeste hain, par kabhi khate nahi?",
    options: ["Taash (Cards)", "Sabzi", "Nakhoon", "Pencil"],
    answer: "Taash (Cards)",
    explanation: "Taash ko 'cut' aur 'shuffle' (peesta) jata hai.",
  },
  {
    id: 71,
    title: "The Echo",
    question: "Main tabhi bolta hoon jab mera naam liya jata hai. Main kaun hoon?",
    options: ["Insaan", "Echo (Goonj)", "Mobile", "Speaker"],
    answer: "Echo (Goonj)",
    explanation: "Echo tabhi sunayi deti hai jab aap awaaz lagate hain.",
  },
  {
    id: 72,
    title: "Lighthouse Jump",
    question: "Ek lighthouse ke upar se ek aadmi ne kood maari par wo bach gaya. Kaise?",
    options: ["Parachute", "Andar ki taraf kooda", "Pani gehra tha", "Superman"],
    answer: "Andar ki taraf kooda",
    explanation: "Wo lighthouse ke andar ki sidhiyon par kooda, bahar nahi.",
  },
  {
    id: 73,
    title: "Traveler Road",
    question: "Wo kya hai jo ek jagah khada rehta hai par poore sheher mein ghumta hai?",
    options: ["Postman", "Road", "Electricity", "Police"],
    answer: "Road",
    explanation: "Sadak poore sheher mein pheli hoti hai par wo hilti nahi.",
  },
  {
    id: 74,
    title: "Sweat",
    question: "Wo kya hai jo thand mein jamta nahi par garmi mein pighal jata hai?",
    options: ["Ice cream", "Mom (Wax)", "Pasina", "Butter"],
    answer: "Pasina",
    explanation: "Pasina garmi mein nikalta hai (interpretive logic).",
  },
  {
    id: 75,
    title: "Odd Palindrome",
    question: "Inmein se kaunsa word 'Odd' hai: Racecar, Level, Madam, Apple?",
    options: ["Racecar", "Level", "Madam", "Apple"],
    answer: "Apple",
    explanation: "Baki sab Palindromes hain (piche se bhi wahi word).",
  },
  {
    id: 76,
    title: "Uninvited Guest",
    question: "Wo kya hai jo bina bulaye aata hai aur bina bataye chala jata hai?",
    options: ["Sapna", "Maut", "Neend", "All of these"],
    answer: "All of these",
    explanation: "Sapna, neend aur maut kabhi bata kar nahi aate.",
  },
  {
    id: 77,
    title: "The Fear of Darkness",
    question: "Wo kya hai jo paas hone par dikhta nahi aur door hone par darr lagta hai?",
    options: ["Bhoot", "Sher", "Andhera", "Maut"],
    answer: "Andhera",
    explanation: "Andhera paas ho toh kuch dikhta nahi, par andheri doori darr paida karti hai.",
  },
  {
    id: 78,
    title: "Changing Answer",
    question: "Wo kaunsa sawal hai jiska jawab badalta rehta hai?",
    options: ["Aapka naam?", "Kya time hua hai?", "Aaj kaunsa din hai?", "B aur C dono"],
    answer: "B aur C dono",
    explanation: "Time aur Din hamesha badalte rehte hain.",
  },
  {
    id: 79,
    title: "The Shroud",
    question: "Wo kya hai jo banate waqt gaya jata hai aur pehente waqt roya jata hai?",
    options: ["Shaadi ka jora", "Kafan", "Uniform", "Party dress"],
    answer: "Kafan",
    explanation: "Kafan (shroud) maut par pehnaya jata hai.",
  },
  {
    id: 80,
    title: "Liar Paradox",
    question: "Agar main kahu ki 'Main hamesha jhoot bolta hoon', toh kya main sach bol raha hoon?",
    options: ["Haan", "Nahi", "Paradox", "Dono galat"],
    answer: "Paradox",
    explanation: "Ye ek logical paradox hai jise kabhi solve nahi kiya ja sakta.",
  }
];
