import React from 'react';

export type Puzzle = {
  id: number;
  title: string;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
};

export const ALL_PUZZLES: Puzzle[] = [
  {
    id: 1,
    title: "False Connection",
    question: "Statement 1: All Lions are Cats.\nStatement 2: Some Cats are Blue.\nConclusion: Therefore, some Lions are Blue.",
    options: ["Logic is TRUE", "Logic is FALSE"],
    answer: "Logic is FALSE",
    explanation: "Standard Syllogism trap. Just because some cats are blue doesn't mean lions (who are cats) must be blue.",
  },
  {
    id: 2,
    title: "Sequence Breaker",
    question: "O, T, T, F, F, S, S, _?",
    options: ["S", "E", "N", "T"],
    answer: "E",
    explanation: "These are the first letters of numbers: One, Two, Three, Four, Five, Six, Seven. The next is Eight (E).",
  },
  {
    id: 3,
    title: "Weight Paradox",
    question: "If 3 Apples weigh the same as 2 Oranges, and 1 Banana is heavier than 1 Orange, which fruit is the heaviest?",
    options: ["Apple", "Orange", "Banana"],
    answer: "Banana",
    explanation: "3A = 2O implies 1O > 1A. Since B > O, then B > O > A. Banana is the heaviest.",
  },
  {
    id: 4,
    title: "Mirror Time",
    question: "A mirror shows an analog clock at 3:45. What is the real time?",
    options: ["3:45", "9:15", "8:15", "9:45"],
    answer: "8:15",
    explanation: "Real Time = 11:60 - Mirror Time. 11:60 - 3:45 = 8:15.",
  },
  {
    id: 5,
    title: "Letter Math",
    question: "A + A = B\nB + A = 6\nWhat is the value of B?",
    options: ["2", "4", "3", "6"],
    answer: "4",
    explanation: "A=2, B=4. 2+2=4 and 4+2=6.",
  },
  {
    id: 6,
    title: "Elevator Logic",
    question: "A man lives on the 10th floor. On rainy days he takes the lift to the 10th. On sunny days, he goes to the 7th and walks the rest. Why?",
    options: ["He likes exercise", "He is short", "The lift is broken", "He visits a friend"],
    answer: "He is short",
    explanation: "He can only reach the 10th button with his umbrella. On sunny days he lacks it and only reaches the 7th.",
  },
  {
    id: 7,
    title: "Silent Syllables",
    question: "How many silent letters are in the word 'PNEUMONIA'?",
    options: ["0", "1", "2", "3"],
    answer: "1",
    explanation: "The 'P' is silent.",
  },
  {
    id: 8,
    title: "Odd Shape Out",
    question: "Which of these does NOT belong?",
    options: ["Circle", "Sphere", "Triangle", "Square"],
    answer: "Sphere",
    explanation: "A Sphere is 3D; the others are 2D shapes.",
  },
  {
    id: 9,
    title: "The Color Path",
    question: "Instruction: Pick the word where Word and Color match.",
    options: ["RED (in Blue)", "GREEN (in Green)", "YELLOW (in Red)", "BLUE (in Yellow)"],
    answer: "GREEN (in Green)",
    explanation: "This tests inhibition. Only Green matches both word and color.",
  },
  {
    id: 10,
    title: "Logic Trap 2",
    question: "A plane crashes on the border of US and Canada. Where do you bury the survivors?",
    options: ["USA", "Canada", "Neutral Ground", "You don't"],
    answer: "You don't",
    explanation: "You don't bury survivors!",
  },
  // New Puzzles - Section 5
  {
    id: 11,
    title: "Family Ties",
    question: "Ek baccha 'A' aur 'B' ka beta hai, lekin 'B' uska baap nahi hai. Toh 'B' kaun hai?",
    options: ["Chacha", "Mausi", "Maa", "Padosi"],
    answer: "Maa",
    explanation: "Agar B baap nahi hai toh wo Maa hi hogi.",
  },
  {
    id: 12,
    title: "The Eternal Arrival",
    question: "Wo kya hai jo hamesha aata hai lekin kabhi pahunchta nahi?",
    options: ["Train", "Kal (Tomorrow)", "Baarish", "Chitti"],
    answer: "Kal (Tomorrow)",
    explanation: "Kal (Tomorrow) hamesha aane wala hota hai par jab aata hai toh wo 'Aaj' ban jata hai.",
  },
  {
    id: 13,
    title: "The Dinner Table",
    question: "Ek mez (Table) par 2 maayein aur 2 betiyan khana kha rahi hain, par wahan sirf 3 hi log hain. Kaise?",
    options: ["Ek bhoot hai", "Nani, Maa aur Beti", "Ek padosi hai", "Rishta galat hai"],
    answer: "Nani, Maa aur Beti",
    explanation: "Nani, unki beti (jo maa hai), aur unki beti (jo poti/beti hai). 2 maayein aur 2 betiyan pure ho gaye.",
  },
  {
    id: 14,
    title: "The Room Trap",
    question: "Ek room mein 3 log hain. Aapne 2 ko maar diya. Ab room mein kitne log bache?",
    options: ["1", "2", "3", "4"],
    answer: "4",
    explanation: "Aap khud, 2 lashein, aur 1 jo bach gaya = 4 log (living and dead) room mein hain.",
  },
  {
    id: 15,
    title: "Broken Utility",
    question: "Wo kya hai jo toote bina kaam nahi karta?",
    options: ["Dil", "Anda (Egg)", "Pencil", "Khilauna"],
    answer: "Anda (Egg)",
    explanation: "Ande ko istemal karne ke liye use todna hi padta hai.",
  },
  {
    id: 16,
    title: "Wall Logic",
    question: "Agar 8 log ek deewar ko banane mein 10 ghante lete hain, toh wahi deewar banane mein 4 log kitna time lenge?",
    options: ["20 ghante", "5 ghante", "Zero", "40 ghante"],
    answer: "Zero",
    explanation: "Deewar toh pehle hi ban chuki hai!",
  },
  {
    id: 17,
    title: "Blind Sight",
    question: "Mere paas aankhen hain par main dekh nahi sakta. Main kaun hoon?",
    options: ["Andha aadmi", "Sui (Needle)", "Aloo (Potato)", "B aur C dono"],
    answer: "B aur C dono",
    explanation: "Sui ki 'aankh' (naka) aur Aloo ki bhi 'aankh' hoti hai.",
  },
  {
    id: 18,
    title: "Dictionary Order",
    question: "Wo kaunsi jagah hai jahan Friday, Thursday se pehle aata hai?",
    options: ["Mars", "Dictionary", "Sapne mein", "Dusra desh"],
    answer: "Dictionary",
    explanation: "Dictionary mein F (Friday) T (Thursday) se pehle aata hai.",
  },
  {
    id: 19,
    title: "Increasing Darkness",
    question: "Wo kya hai jo jitna zyada badhta hai, utna hi kam dikhta hai?",
    options: ["Paisa", "Andhera", "Umra", "Height"],
    answer: "Andhera",
    explanation: "Andhera jitna badhega, utna hi kam dikhayi dega.",
  },
  {
    id: 20,
    title: "The Crash Paradox",
    question: "Ek airplane crash hua aur har ek single person mar gaya. Phir bhi 2 log bach gaye. Kaise?",
    options: ["Plane ke bahar the", "Married couple", "Wo pilot the", "Bhoot ban gaye"],
    answer: "Married couple",
    explanation: "Kyuki wo 'Married' the, 'Single' nahi.",
  },
  // Section 6
  {
    id: 21,
    title: "Hen Math",
    question: "3 murgiyan 3 din mein 3 ande deti hain. Toh 12 murgiyan 12 din mein kitne ande dengi?",
    options: ["12", "36", "48", "144"],
    answer: "48",
    explanation: "1 murgi 3 din mein 1 anda deti hai. 12 murgiyan 3 din mein 12 ande dengi. 12 din mein (12*4) = 48.",
  },
  {
    id: 22,
    title: "The Apple Thief",
    question: "Ek tokri mein 10 seb hain. Aapne 3 seb nikaal liye. Ab aapke paas kitne seb hain?",
    options: ["7", "10", "3", "13"],
    answer: "3",
    explanation: "Jo 3 seb aapne nikaale, wahi aapke paas hain!",
  },
  {
    id: 23,
    title: "Doctor's Prescription",
    question: "Agar ek doctor aapko 3 tablets deta hai aur kehta hai har adhe ghante baad ek leni hai. Kitna time lagega?",
    options: ["1.5 ghante", "1 ghanta", "30 min", "2 ghante"],
    answer: "1 ghanta",
    explanation: "Pehli abhi (0 min), dusri 30 min baad, teesri 60 min baad.",
  },
  {
    id: 24,
    title: "Letter Count",
    question: "How many letters are in 'M-A-N-G-O'?",
    options: ["4", "5", "6", "1"],
    answer: "5",
    explanation: "M-A-N-G-O has exactly 5 letters.",
  },
  {
    id: 25,
    title: "The Drying Towel",
    question: "Wo kya hai jo jitna sukhta hai, utna hi geela hota jata hai?",
    options: ["Pani", "Towel", "Baadal", "Suraj"],
    answer: "Towel",
    explanation: "Towel cheezon ko sukhata hai isliye wo khud geela hota jata hai.",
  },
  // Section 7
  {
    id: 26,
    title: "Infinite Treasure",
    question: "Wo kaunsa khazana hai jise jitna baanto utna badhta hai?",
    options: ["Paisa", "Khana", "Gyan (Knowledge)", "Kapde"],
    answer: "Gyan (Knowledge)",
    explanation: "Gyan (Knowledge) baantne se hamesha badhta hai.",
  },
  {
    id: 27,
    title: "Billi ka Naam",
    question: "Ek billi ke 3 bacche hain: January, February aur March. Billi ka naam kya hai?",
    options: ["April", "What", "Kitty", "Pussy"],
    answer: "What",
    explanation: "Sentence ko dhyan se padhein: 'Billi ka naam (What) hai'.",
  },
  {
    id: 28,
    title: "Invisible Presence",
    question: "Wo kya hai jo hamesha aapke samne hota hai par dikhta nahi?",
    options: ["Hawa", "Bhavishya (Future)", "Palkein", "B aur C dono"],
    answer: "B aur C dono",
    explanation: "Bhavishya aur Palkein hamesha samne hote hain par dikhte nahi.",
  },
  {
    id: 29,
    title: "Un-eatable Purchase",
    question: "Wo kaunsa phal/cheez hai jo hum kharidte toh khane ke liye hain par khate nahi?",
    options: ["Plate", "Chammach", "Dono", "Kela"],
    answer: "Dono",
    explanation: "Plate aur Chammach khane ke 'liye' kharidte hain par unhe khate nahi.",
  },
  {
    id: 30,
    title: "Race Position",
    question: "Agar aap ek race mein dusre (2nd) number wale ko piche chhod dete hain, toh aap kis number par honge?",
    options: ["1st", "2nd", "3rd", "Last"],
    answer: "2nd",
    explanation: "Aapne 2nd wale ki jagah le li, isliye aap ab 2nd position par hain.",
  }
];
